//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//INSTANT C# NOTE: Formerly VB project-level imports:
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System;

namespace BrowserLock
{
	namespace Properties
	{

		//This class was auto-generated by the StronglyTypedResourceBuilder
		//class via a tool like ResGen or Visual Studio.
		//To add or remove a member, edit your .ResX file then rerun ResGen
		//with the /str option, or rebuild your VS project.
		///<summary>
		///  A strongly-typed resource class, for looking up localized strings, etc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal static class Resources
		{

			private static global::System.Resources.ResourceManager resourceMan;

			private static global::System.Globalization.CultureInfo resourceCulture;

			///<summary>
			///  Returns the cached ResourceManager instance used by this class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserLock.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			///<summary>
			///  Overrides the current thread's CurrentUICulture property for all
			///  resource lookups using this strongly typed resource class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			internal static System.Drawing.Bitmap BrowserLock2
			{
				get
				{
					object obj = ResourceManager.GetObject("BrowserLock2", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Icon BrowserLock21
			{
				get
				{
					object obj = ResourceManager.GetObject("BrowserLock21", resourceCulture);
					return (System.Drawing.Icon)obj;
				}
			}

			internal static System.Drawing.Bitmap check
			{
				get
				{
					object obj = ResourceManager.GetObject("check", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap email_icon_16x16
			{
				get
				{
					object obj = ResourceManager.GetObject("email_icon_16x16", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap Facebook_icon__1_
			{
				get
				{
					object obj = ResourceManager.GetObject("Facebook_icon__1_", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap folderopen
			{
				get
				{
					object obj = ResourceManager.GetObject("folderopen", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap play
			{
				get
				{
					object obj = ResourceManager.GetObject("play", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap root
			{
				get
				{
					object obj = ResourceManager.GetObject("root", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap save
			{
				get
				{
					object obj = ResourceManager.GetObject("save", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap TPD_Starburst_16x16
			{
				get
				{
					object obj = ResourceManager.GetObject("TPD_Starburst_16x16", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap TrialExpired
			{
				get
				{
					object obj = ResourceManager.GetObject("TrialExpired", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap twitter_newbird_boxed_blueonwhite
			{
				get
				{
					object obj = ResourceManager.GetObject("twitter_newbird_boxed_blueonwhite", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap x
			{
				get
				{
					object obj = ResourceManager.GetObject("x", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			internal static System.Drawing.Bitmap Youtube_icon
			{
				get
				{
					object obj = ResourceManager.GetObject("Youtube_icon", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}
		}
	}

}